[build.nixpacksPlan.phases.setup]
nixPkgs = ['...', 'unzip']

[build]
builder = "NIXPACKS"
buildCommand = "bun upgrade"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
