[build]
builder = "NIXPACKS"
nixpkgsArchive = 'a3c637e0abe5e459370fe5cde53496ed2ec301ed'

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
