[build]
builder = "NIXPACKS"
buildCommand = "echo building!"

[deploy]
startCommand = "echo starting!"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
